spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1060128516661-m622grkjbgn1lmnf41k4q967ku782a6c.apps.googleusercontent.com
            client-secret: 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
